import os

SETTINGS_FILE = "Web/settings.js"

def load_settings():
    # Simple parser for our specific JS file format
    settings = {}
    if os.path.exists(SETTINGS_FILE):
        with open(SETTINGS_FILE, "r") as f:
            for line in f:
                if ":" in line and '"' in line:
                    parts = line.split(":")
                    key = parts[0].strip().replace('"', '')
                    val = parts[1].strip().replace('"', '').replace(',', '')
                    settings[key] = val
    return settings

def save_settings(settings):
    content = """// This file is automatically generated by configure.py
// Do not edit manually if possible.

const AppConfig = {
"""
    for key, val in settings.items():
        content += f'    "{key}": "{val}",\n'
    
    content += "};\n"
    
    with open(SETTINGS_FILE, "w") as f:
        f.write(content)
    print(f"Saved configuration to {SETTINGS_FILE}")

def main():
    print("--- BetclicPredictor Admin Panel ---")
    print("1. Update Payment Links (Stripe)")
    print("2. Run Betting Strategy (Update Predictions)")
    print("3. Exit")
    
    choice = input("Select an option (1-3): ")
    
    if choice == "1":
        settings = load_settings()
        
        print("\nEnter your Stripe Payment Link for the MONTHLY Plan.")
        print("Example: https://buy.stripe.com/test_12345")
        monthly = input(f"Current [{settings.get('STRIPE_MONTHLY_URL', '#')}]: ").strip()
        if monthly:
            settings['STRIPE_MONTHLY_URL'] = monthly
            
        print("\nEnter your Stripe Payment Link for the YEARLY Plan.")
        yearly = input(f"Current [{settings.get('STRIPE_YEARLY_URL', '#')}]: ").strip()
        if yearly:
            settings['STRIPE_YEARLY_URL'] = yearly
            
        save_settings(settings)
        print("\nSUCCESS: Payment links updated. Redeploy your site to apply changes.")
        
    elif choice == "2":
        print("\nRunning Strategy Engine...")
        os.system("python strategy_engine.py")
        print("\nSUCCESS: Predictions updated.")
        
    elif choice == "3":
        print("Goodbye.")
    else:
        print("Invalid option.")

if __name__ == "__main__":
    main()
